name: movies
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  dio: ^5.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  get: ^4.6.5
  get_it: ^7.2.0
  get_storage: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.0
  lottie: ^2.3.1
  number_paginator: ^0.2.3
  youtube_player_flutter: ^8.1.2
  flutter_native_splash: ^2.2.19

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter_icons:
  android: true
  image_path: "assets/images/png/logo.png"  


flutter_native_splash:
  color: "#040404"
  image: assets/images/png/splash.png
  android: true
  ios: true
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
